version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1os3mj73cd0l9"
s3_prefix = "test-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

